[package]
name = "queue-task"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "*"
actix-files = "*"
tokio = "*"
actix-cors = "*"
serde = { version = "1.0", features = ["derive"] }
mongodb = "3.1.0"
futures = "0.3.31"